# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherlock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='searching_for',
            field=models.CharField(blank=True, choices=[('Cousin', 'Cousin'), ('Child', 'Child'), ('Parent', 'Parent'), ('Sibling', 'Sibling'), ('Aunt', 'Aunt'), ('Uncle', 'Uncle'), ('Grandparent', 'Grandparent')], max_length=20),
        ),
    ]
