# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherlock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.FileField(default='setting.STATIC_ROOT/picture.png', upload_to=''),
        ),
    ]
