# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherlock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.FileField(upload_to='album_img'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.FileField(upload_to='profile_img'),
        ),
    ]
