# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherlock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
