# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-29 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherlock', '0002_auto_20161128_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='biography',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='sex_at_birth',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.FileField(blank=True, upload_to='album_img'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.FileField(blank=True, upload_to='profile_img'),
        ),
    ]
