# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sherlock', '0003_auto_20161121_1732'),
        ('sherlock', '0003_auto_20161121_1731'),
    ]

    operations = [
    ]
