# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherlock', '0004_merge_20161121_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='relative',
            name='similarity',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
