# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sherlock', '0006_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='biography',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
